--- createnobel, 1, 50
CREATE TABLE nobel(
  yr INT
 ,subject VARCHAR(15)
 ,winner VARCHAR(50)
);
--- tabnobel, 1, 50
insert into nobel values (2008,'Chemistry','Martin Chalfie');
insert into nobel values (2008,'Chemistry','Osamu Shimomura');
insert into nobel values (2008,'Chemistry','Roger Y. Tsien');
insert into nobel values (2008,'Economics','Paul Krugman');
insert into nobel values (2008,'Literature','Jean-Marie Gustave Le Clézio');
insert into nobel values (2008,'Medicine','Françoise Barré-Sinoussi');
insert into nobel values (2008,'Medicine','Luc Montagnier');
insert into nobel values (2008,'Medicine','Harald zur Hausen');
insert into nobel values (2008,'Peace','Martti Ahtisaari');
insert into nobel values (2008,'Physics','Makoto Kobayashi');
insert into nobel values (2008,'Physics','Toshihide Maskawa');
insert into nobel values (2008,'Physics','Yoichiro Nambu');
insert into nobel values (2007,'Chemistry','Gerhard Ertl');
insert into nobel values (2007,'Economics','Leonid Hurwicz');
insert into nobel values (2007,'Economics','Eric S. Maskin');
insert into nobel values (2007,'Economics','Roger B. Myerson');
insert into nobel values (2007,'Literature','Doris Lessing');
insert into nobel values (2007,'Medicine','Mario R. Capecchi');
insert into nobel values (2007,'Medicine','Sir Martin J. Evans');
insert into nobel values (2007,'Medicine','Oliver Smithies');
insert into nobel values (2007,'Peace','Intergovernmental Panel on Climate Change');
insert into nobel values (2007,'Peace','Al Gore');
insert into nobel values (2007,'Physics','Albert Fert');
insert into nobel values (2007,'Physics','Peter Grünberg');
insert into nobel values (2006,'Chemistry','Roger D. Kornberg');
insert into nobel values (2006,'Economics','Edmund S. Phelps');
insert into nobel values (2006,'Literature','Orhan Pamuk');
insert into nobel values (2006,'Medicine','Andrew Z. Fire');
insert into nobel values (2006,'Medicine','Craig C. Mello');
insert into nobel values (2006,'Peace','Grameen Bank');
insert into nobel values (2006,'Peace','Muhammad Yunus');
insert into nobel values (2006,'Physics','John C. Mather');
insert into nobel values (2006,'Physics','George F. Smoot');
insert into nobel values (2005,'Chemistry','Yves Chauvin');
insert into nobel values (2005,'Chemistry','Robert H. Grubbs');
insert into nobel values (2005,'Chemistry','Richard R. Schrock');
insert into nobel values (2005,'Economics','Robert J. Aumann');
insert into nobel values (2005,'Economics','Thomas C. Schelling');
insert into nobel values (2005,'Literature','Harold Pinter');
insert into nobel values (2005,'Medicine','Barry J. Marshall');
insert into nobel values (2005,'Medicine','J. Robin Warren');
insert into nobel values (2005,'Peace','International Atomic Energy Agency');
insert into nobel values (2005,'Peace','Mohamed ElBaradei');
insert into nobel values (2005,'Physics','Roy J. Glauber');
insert into nobel values (2005,'Physics','John L. Hall');
insert into nobel values (2005,'Physics','Theodor W. Hänsch');
insert into nobel values (2004,'Chemistry','Aaron Ciechanover');
insert into nobel values (2004,'Chemistry','Avram Hershko');
insert into nobel values (2004,'Chemistry','Irwin Rose');
insert into nobel values (2004,'Economics','Finn E. Kydland');
--- tabnobel, 51, 50
insert into nobel values (2004,'Economics','Edward C. Prescott');
insert into nobel values (2004,'Literature','Elfriede Jelinek');
insert into nobel values (2004,'Medicine','Richard Axel');
insert into nobel values (2004,'Medicine','Linda B. Buck');
insert into nobel values (2004,'Peace','Wangari Maathai');
insert into nobel values (2004,'Physics','David J. Gross');
insert into nobel values (2004,'Physics','H. David Politzer');
insert into nobel values (2004,'Physics','Frank Wilczek');
insert into nobel values (2003,'Chemistry','Peter Agre');
insert into nobel values (2003,'Chemistry','Roderick MacKinnon');
insert into nobel values (2003,'Economics','Robert F. Engle III');
insert into nobel values (2003,'Economics','Clive W.J. Granger');
insert into nobel values (2003,'Literature','J. M. Coetzee');
insert into nobel values (2003,'Medicine','Paul C. Lauterbur');
insert into nobel values (2003,'Medicine','Sir Peter Mansfield');
insert into nobel values (2003,'Peace','Shirin Ebadi');
insert into nobel values (2003,'Physics','Alexei A. Abrikosov');
insert into nobel values (2003,'Physics','Vitaly L. Ginzburg');
insert into nobel values (2003,'Physics','Anthony J. Leggett');
insert into nobel values (2002,'Chemistry','John B. Fenn');
insert into nobel values (2002,'Chemistry','Koichi Tanaka');
insert into nobel values (2002,'Chemistry','Kurt Wüthrich');
insert into nobel values (2002,'Economics','Daniel Kahneman');
insert into nobel values (2002,'Economics','Vernon L. Smith');
insert into nobel values (2002,'Literature','Imre Kertész');
insert into nobel values (2002,'Medicine','Sydney Brenner');
insert into nobel values (2002,'Medicine','H. Robert Horvitz');
insert into nobel values (2002,'Medicine','John E. Sulston');
insert into nobel values (2002,'Peace','Jimmy Carter');
insert into nobel values (2002,'Physics','Raymond Davis Jr.');
insert into nobel values (2002,'Physics','Riccardo Giacconi');
insert into nobel values (2002,'Physics','Masatoshi Koshiba');
insert into nobel values (2001,'Chemistry','William S. Knowles');
insert into nobel values (2001,'Chemistry','Ryoji Noyori');
insert into nobel values (2001,'Chemistry','K. Barry Sharpless');
insert into nobel values (2001,'Economics','George A. Akerlof');
insert into nobel values (2001,'Economics','A. Michael Spence');
insert into nobel values (2001,'Economics','Joseph E. Stiglitz');
insert into nobel values (2001,'Literature','V. S. Naipaul');
insert into nobel values (2001,'Medicine','Leland H. Hartwell');
insert into nobel values (2001,'Medicine','Tim Hunt');
insert into nobel values (2001,'Medicine','Sir Paul Nurse');
insert into nobel values (2001,'Peace','United Nations');
insert into nobel values (2001,'Peace','Kofi Annan');
insert into nobel values (2001,'Physics','Eric A. Cornell');
insert into nobel values (2001,'Physics','Wolfgang Ketterle');
insert into nobel values (2001,'Physics','Carl E. Wieman');
insert into nobel values (2000,'Chemistry','Alan Heeger');
insert into nobel values (2000,'Chemistry','Alan G. MacDiarmid');
insert into nobel values (2000,'Chemistry','Hideki Shirakawa');
--- tabnobel, 101, 50
insert into nobel values (2000,'Economics','James J. Heckman');
insert into nobel values (2000,'Economics','Daniel L. McFadden');
insert into nobel values (2000,'Literature','Gao Xingjian');
insert into nobel values (2000,'Medicine','Arvid Carlsson');
insert into nobel values (2000,'Medicine','Paul Greengard');
insert into nobel values (2000,'Medicine','Eric R. Kandel');
insert into nobel values (2000,'Peace','Kim Dae-jung');
insert into nobel values (2000,'Physics','Zhores I. Alferov');
insert into nobel values (2000,'Physics','Jack S. Kilby');
insert into nobel values (2000,'Physics','Herbert Kroemer');
insert into nobel values (1999,'Chemistry','Ahmed Zewail');
insert into nobel values (1999,'Economics','Robert A. Mundell');
insert into nobel values (1999,'Literature','Günter Grass');
insert into nobel values (1999,'Medicine','Günter Blobel');
insert into nobel values (1999,'Peace','Médecins Sans Frontières');
insert into nobel values (1999,'Physics','Gerardus ''''t Hooft');
insert into nobel values (1999,'Physics','Martinus J.G. Veltman');
insert into nobel values (1998,'Chemistry','Walter Kohn');
insert into nobel values (1998,'Chemistry','John Pople');
insert into nobel values (1998,'Economics','Amartya Sen');
insert into nobel values (1998,'Literature','José Saramago');
insert into nobel values (1998,'Medicine','Robert F. Furchgott');
insert into nobel values (1998,'Medicine','Louis J. Ignarro');
insert into nobel values (1998,'Medicine','Ferid Murad');
insert into nobel values (1998,'Peace','John Hume');
insert into nobel values (1998,'Peace','David Trimble');
insert into nobel values (1998,'Physics','Robert B. Laughlin');
insert into nobel values (1998,'Physics','Horst L. Störmer');
insert into nobel values (1998,'Physics','Daniel C. Tsui');
insert into nobel values (1997,'Chemistry','Paul D. Boyer');
insert into nobel values (1997,'Chemistry','Jens C. Skou');
insert into nobel values (1997,'Chemistry','John E. Walker');
insert into nobel values (1997,'Economics','Robert C. Merton');
insert into nobel values (1997,'Economics','Myron S. Scholes');
insert into nobel values (1997,'Literature','Dario Fo');
insert into nobel values (1997,'Medicine','Stanley B. Prusiner');
insert into nobel values (1997,'Peace','International Campaign to Ban Landmines');
insert into nobel values (1997,'Peace','Jody Williams');
insert into nobel values (1997,'Physics','Steven Chu');
insert into nobel values (1997,'Physics','Claude Cohen-Tannoudji');
insert into nobel values (1997,'Physics','William D. Phillips');
insert into nobel values (1996,'Chemistry','Robert F. Curl Jr.');
insert into nobel values (1996,'Chemistry','Sir Harold Kroto');
insert into nobel values (1996,'Chemistry','Richard E. Smalley');
insert into nobel values (1996,'Economics','James A. Mirrlees');
insert into nobel values (1996,'Economics','William Vickrey');
insert into nobel values (1996,'Literature','Wislawa Szymborska');
insert into nobel values (1996,'Medicine','Peter C. Doherty');
insert into nobel values (1996,'Medicine','Rolf M. Zinkernagel');
insert into nobel values (1996,'Peace','Carlos Filipe Ximenes Belo');
--- tabnobel, 151, 50
insert into nobel values (1996,'Peace','José Ramos-Horta');
insert into nobel values (1996,'Physics','David M. Lee');
insert into nobel values (1996,'Physics','Douglas D. Osheroff');
insert into nobel values (1996,'Physics','Robert C. Richardson');
insert into nobel values (1995,'Chemistry','Paul J. Crutzen');
insert into nobel values (1995,'Chemistry','Mario J. Molina');
insert into nobel values (1995,'Chemistry','F. Sherwood Rowland');
insert into nobel values (1995,'Economics','Robert E. Lucas Jr.');
insert into nobel values (1995,'Literature','Seamus Heaney');
insert into nobel values (1995,'Medicine','Edward B. Lewis');
insert into nobel values (1995,'Medicine','Christiane Nüsslein-Volhard');
insert into nobel values (1995,'Medicine','Eric F. Wieschaus');
insert into nobel values (1995,'Peace','Pugwash Conferences on Science and World Affairs');
insert into nobel values (1995,'Peace','Joseph Rotblat');
insert into nobel values (1995,'Physics','Martin L. Perl');
insert into nobel values (1995,'Physics','Frederick Reines');
insert into nobel values (1994,'Chemistry','George A. Olah');
insert into nobel values (1994,'Economics','John C. Harsanyi');
insert into nobel values (1994,'Economics','John F. Nash Jr.');
insert into nobel values (1994,'Economics','Reinhard Selten');
insert into nobel values (1994,'Literature','Kenzaburo Oe');
insert into nobel values (1994,'Medicine','Alfred G. Gilman');
insert into nobel values (1994,'Medicine','Martin Rodbell');
insert into nobel values (1994,'Peace','Yasser Arafat');
insert into nobel values (1994,'Peace','Shimon Peres');
insert into nobel values (1994,'Peace','Yitzhak Rabin');
insert into nobel values (1994,'Physics','Bertram N. Brockhouse');
insert into nobel values (1994,'Physics','Clifford G. Shull');
insert into nobel values (1993,'Chemistry','Kary B. Mullis');
insert into nobel values (1993,'Chemistry','Michael Smith');
insert into nobel values (1993,'Economics','Robert W. Fogel');
insert into nobel values (1993,'Economics','Douglass C. North');
insert into nobel values (1993,'Literature','Toni Morrison');
insert into nobel values (1993,'Medicine','Richard J. Roberts');
insert into nobel values (1993,'Medicine','Phillip A. Sharp');
insert into nobel values (1993,'Peace','F.W. de Klerk');
insert into nobel values (1993,'Peace','Nelson Mandela');
insert into nobel values (1993,'Physics','Russell A. Hulse');
insert into nobel values (1993,'Physics','Joseph H. Taylor Jr.');
insert into nobel values (1992,'Chemistry','Rudolph A. Marcus');
insert into nobel values (1992,'Economics','Gary S. Becker');
insert into nobel values (1992,'Literature','Derek Walcott');
insert into nobel values (1992,'Medicine','Edmond H. Fischer');
insert into nobel values (1992,'Medicine','Edwin G. Krebs');
insert into nobel values (1992,'Peace','Rigoberta Menchú Tum');
insert into nobel values (1992,'Physics','Georges Charpak');
insert into nobel values (1991,'Chemistry','Richard R. Ernst');
insert into nobel values (1991,'Economics','Ronald H. Coase');
insert into nobel values (1991,'Literature','Nadine Gordimer');
insert into nobel values (1991,'Medicine','Erwin Neher');
--- tabnobel, 201, 50
insert into nobel values (1991,'Medicine','Bert Sakmann');
insert into nobel values (1991,'Peace','Aung San Suu Kyi');
insert into nobel values (1991,'Physics','Pierre-Gilles de Gennes');
insert into nobel values (1990,'Chemistry','Elias James Corey');
insert into nobel values (1990,'Economics','Harry M. Markowitz');
insert into nobel values (1990,'Economics','Merton H. Miller');
insert into nobel values (1990,'Economics','William F. Sharpe');
insert into nobel values (1990,'Literature','Octavio Paz');
insert into nobel values (1990,'Medicine','Joseph E. Murray');
insert into nobel values (1990,'Medicine','E. Donnall Thomas');
insert into nobel values (1990,'Peace','Mikhail Gorbachev');
insert into nobel values (1990,'Physics','Jerome I. Friedman');
insert into nobel values (1990,'Physics','Henry W. Kendall');
insert into nobel values (1990,'Physics','Richard E. Taylor');
insert into nobel values (1989,'Chemistry','Sidney Altman');
insert into nobel values (1989,'Chemistry','Thomas R. Cech');
insert into nobel values (1989,'Economics','Trygve Haavelmo');
insert into nobel values (1989,'Literature','Camilo José Cela');
insert into nobel values (1989,'Medicine','J. Michael Bishop');
insert into nobel values (1989,'Medicine','Harold E. Varmus');
insert into nobel values (1989,'Peace','The 14th Dalai Lama');
insert into nobel values (1989,'Physics','Hans G. Dehmelt');
insert into nobel values (1989,'Physics','Wolfgang Paul');
insert into nobel values (1989,'Physics','Norman F. Ramsey');
insert into nobel values (1988,'Chemistry','Johann Deisenhofer');
insert into nobel values (1988,'Chemistry','Robert Huber');
insert into nobel values (1988,'Chemistry','Hartmut Michel');
insert into nobel values (1988,'Economics','Maurice Allais');
insert into nobel values (1988,'Literature','Naguib Mahfouz');
insert into nobel values (1988,'Medicine','Sir James W. Black');
insert into nobel values (1988,'Medicine','Gertrude B. Elion');
insert into nobel values (1988,'Medicine','George H. Hitchings');
insert into nobel values (1988,'Peace','United Nations Peacekeeping Forces');
insert into nobel values (1988,'Physics','Leon M. Lederman');
insert into nobel values (1988,'Physics','Melvin Schwartz');
insert into nobel values (1988,'Physics','Jack Steinberger');
insert into nobel values (1987,'Chemistry','Donald J. Cram');
insert into nobel values (1987,'Chemistry','Jean-Marie Lehn');
insert into nobel values (1987,'Chemistry','Charles J. Pedersen');
insert into nobel values (1987,'Economics','Robert M. Solow');
insert into nobel values (1987,'Literature','Joseph Brodsky');
insert into nobel values (1987,'Medicine','Susumu Tonegawa');
insert into nobel values (1987,'Peace','Oscar Arias Sánchez');
insert into nobel values (1987,'Physics','J. Georg Bednorz');
insert into nobel values (1987,'Physics','K. Alex Müller');
insert into nobel values (1986,'Chemistry','Dudley R. Herschbach');
insert into nobel values (1986,'Chemistry','Yuan T. Lee');
insert into nobel values (1986,'Chemistry','John C. Polanyi');
insert into nobel values (1986,'Economics','James M. Buchanan Jr.');
insert into nobel values (1986,'Literature','Wole Soyinka');
--- tabnobel, 251, 50
insert into nobel values (1986,'Medicine','Stanley Cohen');
insert into nobel values (1986,'Medicine','Rita Levi-Montalcini');
insert into nobel values (1986,'Peace','Elie Wiesel');
insert into nobel values (1986,'Physics','Gerd Binnig');
insert into nobel values (1986,'Physics','Heinrich Rohrer');
insert into nobel values (1986,'Physics','Ernst Ruska');
insert into nobel values (1985,'Chemistry','Herbert A. Hauptman');
insert into nobel values (1985,'Chemistry','Jerome Karle');
insert into nobel values (1985,'Economics','Franco Modigliani');
insert into nobel values (1985,'Literature','Claude Simon');
insert into nobel values (1985,'Medicine','Michael S. Brown');
insert into nobel values (1985,'Medicine','Joseph L. Goldstein');
insert into nobel values (1985,'Peace','International Physicians for the Prevention of Nuclear War');
insert into nobel values (1985,'Physics','Klaus von Klitzing');
insert into nobel values (1984,'Chemistry','Bruce Merrifield');
insert into nobel values (1984,'Economics','Richard Stone');
insert into nobel values (1984,'Literature','Jaroslav Seifert');
insert into nobel values (1984,'Medicine','Niels K. Jerne');
insert into nobel values (1984,'Medicine','Georges J.F. Köhler');
insert into nobel values (1984,'Medicine','César Milstein');
insert into nobel values (1984,'Peace','Desmond Tutu');
insert into nobel values (1984,'Physics','Carlo Rubbia');
insert into nobel values (1984,'Physics','Simon van der Meer');
insert into nobel values (1983,'Chemistry','Henry Taube');
insert into nobel values (1983,'Economics','Gerard Debreu');
insert into nobel values (1983,'Literature','William Golding');
insert into nobel values (1983,'Medicine','Barbara McClintock');
insert into nobel values (1983,'Peace','Lech Walesa');
insert into nobel values (1983,'Physics','Subramanyan Chandrasekhar');
insert into nobel values (1983,'Physics','William A. Fowler');
insert into nobel values (1982,'Chemistry','Aaron Klug');
insert into nobel values (1982,'Economics','George J. Stigler');
insert into nobel values (1982,'Literature','Gabriel García Márquez');
insert into nobel values (1982,'Medicine','Sune K. Bergström');
insert into nobel values (1982,'Medicine','Bengt I. Samuelsson');
insert into nobel values (1982,'Medicine','John R. Vane');
insert into nobel values (1982,'Peace','Alfonso García Robles');
insert into nobel values (1982,'Peace','Alva Myrdal');
insert into nobel values (1982,'Physics','Kenneth G. Wilson');
insert into nobel values (1981,'Chemistry','Kenichi Fukui');
insert into nobel values (1981,'Chemistry','Roald Hoffmann');
insert into nobel values (1981,'Economics','James Tobin');
insert into nobel values (1981,'Literature','Elias Canetti');
insert into nobel values (1981,'Medicine','David H. Hubel');
insert into nobel values (1981,'Medicine','Roger W. Sperry');
insert into nobel values (1981,'Medicine','Torsten N. Wiesel');
insert into nobel values (1981,'Peace','Office of the United Nations High Commissioner for Refugees');
insert into nobel values (1981,'Physics','Nicolaas Bloembergen');
insert into nobel values (1981,'Physics','Arthur L. Schawlow');
insert into nobel values (1981,'Physics','Kai M. Siegbahn');
--- tabnobel, 301, 50
insert into nobel values (1980,'Chemistry','Paul Berg');
insert into nobel values (1980,'Chemistry','Walter Gilbert');
insert into nobel values (1980,'Chemistry','Frederick Sanger');
insert into nobel values (1980,'Economics','Lawrence R. Klein');
insert into nobel values (1980,'Literature','Czeslaw Milosz');
insert into nobel values (1980,'Medicine','Baruj Benacerraf');
insert into nobel values (1980,'Medicine','Jean Dausset');
insert into nobel values (1980,'Medicine','George D. Snell');
insert into nobel values (1980,'Peace','Adolfo Pérez Esquivel');
insert into nobel values (1980,'Physics','James Cronin');
insert into nobel values (1980,'Physics','Val Fitch');
insert into nobel values (1979,'Chemistry','Herbert C. Brown');
insert into nobel values (1979,'Chemistry','Georg Wittig');
insert into nobel values (1979,'Economics','Sir Arthur Lewis');
insert into nobel values (1979,'Economics','Theodore W. Schultz');
insert into nobel values (1979,'Literature','Odysseus Elytis');
insert into nobel values (1979,'Medicine','Allan M. Cormack');
insert into nobel values (1979,'Medicine','Godfrey N. Hounsfield');
insert into nobel values (1979,'Peace','Mother Teresa');
insert into nobel values (1979,'Physics','Sheldon Glashow');
insert into nobel values (1979,'Physics','Abdus Salam');
insert into nobel values (1979,'Physics','Steven Weinberg');
insert into nobel values (1978,'Chemistry','Peter Mitchell');
insert into nobel values (1978,'Economics','Herbert A. Simon');
insert into nobel values (1978,'Literature','Isaac Bashevis Singer');
insert into nobel values (1978,'Medicine','Werner Arber');
insert into nobel values (1978,'Medicine','Daniel Nathans');
insert into nobel values (1978,'Medicine','Hamilton O. Smith');
insert into nobel values (1978,'Peace','Anwar al-Sadat');
insert into nobel values (1978,'Peace','Menachem Begin');
insert into nobel values (1978,'Physics','Pyotr Kapitsa');
insert into nobel values (1978,'Physics','Arno Penzias');
insert into nobel values (1978,'Physics','Robert Woodrow Wilson');
insert into nobel values (1977,'Chemistry','Ilya Prigogine');
insert into nobel values (1977,'Economics','James E. Meade');
insert into nobel values (1977,'Economics','Bertil Ohlin');
insert into nobel values (1977,'Literature','Vicente Aleixandre');
insert into nobel values (1977,'Medicine','Roger Guillemin');
insert into nobel values (1977,'Medicine','Andrew V. Schally');
insert into nobel values (1977,'Medicine','Rosalyn Yalow');
insert into nobel values (1977,'Peace','Amnesty International');
insert into nobel values (1977,'Physics','Philip W. Anderson');
insert into nobel values (1977,'Physics','Sir Nevill F. Mott');
insert into nobel values (1977,'Physics','John H. van Vleck');
insert into nobel values (1976,'Chemistry','William Lipscomb');
insert into nobel values (1976,'Economics','Milton Friedman');
insert into nobel values (1976,'Literature','Saul Bellow');
insert into nobel values (1976,'Medicine','Baruch S. Blumberg');
insert into nobel values (1976,'Medicine','D. Carleton Gajdusek');
insert into nobel values (1976,'Peace','Mairead Corrigan');
--- tabnobel, 351, 50
insert into nobel values (1976,'Peace','Betty Williams');
insert into nobel values (1976,'Physics','Burton Richter');
insert into nobel values (1976,'Physics','Samuel C.C. Ting');
insert into nobel values (1975,'Chemistry','John Cornforth');
insert into nobel values (1975,'Chemistry','Vladimir Prelog');
insert into nobel values (1975,'Economics','Leonid Vitaliyevich Kantorovich');
insert into nobel values (1975,'Economics','Tjalling C. Koopmans');
insert into nobel values (1975,'Literature','Eugenio Montale');
insert into nobel values (1975,'Medicine','David Baltimore');
insert into nobel values (1975,'Medicine','Renato Dulbecco');
insert into nobel values (1975,'Medicine','Howard M. Temin');
insert into nobel values (1975,'Peace','Andrei Sakharov');
insert into nobel values (1975,'Physics','Aage N. Bohr');
insert into nobel values (1975,'Physics','Ben R. Mottelson');
insert into nobel values (1975,'Physics','James Rainwater');
insert into nobel values (1974,'Chemistry','Paul J. Flory');
insert into nobel values (1974,'Economics','Gunnar Myrdal');
insert into nobel values (1974,'Economics','Friedrich August von Hayek');
insert into nobel values (1974,'Literature','Eyvind Johnson');
insert into nobel values (1974,'Literature','Harry Martinson');
insert into nobel values (1974,'Medicine','Albert Claude');
insert into nobel values (1974,'Medicine','Christian de Duve');
insert into nobel values (1974,'Medicine','George E. Palade');
insert into nobel values (1974,'Peace','Seán MacBride');
insert into nobel values (1974,'Peace','Eisaku Sato');
insert into nobel values (1974,'Physics','Antony Hewish');
insert into nobel values (1974,'Physics','Martin Ryle');
insert into nobel values (1973,'Chemistry','Ernst Otto Fischer');
insert into nobel values (1973,'Chemistry','Geoffrey Wilkinson');
insert into nobel values (1973,'Economics','Wassily Leontief');
insert into nobel values (1973,'Literature','Patrick White');
insert into nobel values (1973,'Medicine','Konrad Lorenz');
insert into nobel values (1973,'Medicine','Nikolaas Tinbergen');
insert into nobel values (1973,'Medicine','Karl von Frisch');
insert into nobel values (1973,'Peace','Le Duc Tho');
insert into nobel values (1973,'Peace','Henry Kissinger');
insert into nobel values (1973,'Physics','Leo Esaki');
insert into nobel values (1973,'Physics','Ivar Giaever');
insert into nobel values (1973,'Physics','Brian D. Josephson');
insert into nobel values (1972,'Chemistry','Christian Anfinsen');
insert into nobel values (1972,'Chemistry','Stanford Moore');
insert into nobel values (1972,'Chemistry','William H. Stein');
insert into nobel values (1972,'Economics','Kenneth J. Arrow');
insert into nobel values (1972,'Economics','John R. Hicks');
insert into nobel values (1972,'Literature','Heinrich Böll');
insert into nobel values (1972,'Medicine','Gerald M. Edelman');
insert into nobel values (1972,'Medicine','Rodney R. Porter');
insert into nobel values (1972,'Physics','John Bardeen');
insert into nobel values (1972,'Physics','Leon N. Cooper');
insert into nobel values (1972,'Physics','Robert Schrieffer');
--- tabnobel, 401, 50
insert into nobel values (1971,'Chemistry','Gerhard Herzberg');
insert into nobel values (1971,'Economics','Simon Kuznets');
insert into nobel values (1971,'Literature','Pablo Neruda');
insert into nobel values (1971,'Medicine','Earl W. Sutherland, Jr.');
insert into nobel values (1971,'Peace','Willy Brandt');
insert into nobel values (1971,'Physics','Dennis Gabor');
insert into nobel values (1970,'Chemistry','Luis Leloir');
insert into nobel values (1970,'Economics','Paul A. Samuelson');
insert into nobel values (1970,'Literature','Alexandr Solzhenitsyn');
insert into nobel values (1970,'Medicine','Julius Axelrod');
insert into nobel values (1970,'Medicine','Sir Bernard Katz');
insert into nobel values (1970,'Medicine','Ulf von Euler');
insert into nobel values (1970,'Peace','Norman Borlaug');
insert into nobel values (1970,'Physics','Hannes Alfvén');
insert into nobel values (1970,'Physics','Louis Néel');
insert into nobel values (1969,'Chemistry','Derek Barton');
insert into nobel values (1969,'Chemistry','Odd Hassel');
insert into nobel values (1969,'Economics','Ragnar Frisch');
insert into nobel values (1969,'Economics','Jan Tinbergen');
insert into nobel values (1969,'Literature','Samuel Beckett');
insert into nobel values (1969,'Medicine','Max Delbrück');
insert into nobel values (1969,'Medicine','Alfred D. Hershey');
insert into nobel values (1969,'Medicine','Salvador E. Luria');
insert into nobel values (1969,'Peace','International Labour Organization');
insert into nobel values (1969,'Physics','Murray Gell-Mann');
insert into nobel values (1968,'Chemistry','Lars Onsager');
insert into nobel values (1968,'Literature','Yasunari Kawabata');
insert into nobel values (1968,'Medicine','Robert W. Holley');
insert into nobel values (1968,'Medicine','H. Gobind Khorana');
insert into nobel values (1968,'Medicine','Marshall W. Nirenberg');
insert into nobel values (1968,'Peace','René Cassin');
insert into nobel values (1968,'Physics','Luis Alvarez');
insert into nobel values (1967,'Chemistry','Manfred Eigen');
insert into nobel values (1967,'Chemistry','Ronald G.W. Norrish');
insert into nobel values (1967,'Chemistry','George Porter');
insert into nobel values (1967,'Literature','Miguel Angel Asturias');
insert into nobel values (1967,'Medicine','Ragnar Granit');
insert into nobel values (1967,'Medicine','Haldan K. Hartline');
insert into nobel values (1967,'Medicine','George Wald');
insert into nobel values (1967,'Physics','Hans Bethe');
insert into nobel values (1966,'Chemistry','Robert S. Mulliken');
insert into nobel values (1966,'Literature','Shmuel Agnon');
insert into nobel values (1966,'Literature','Nelly Sachs');
insert into nobel values (1966,'Medicine','Charles B. Huggins');
insert into nobel values (1966,'Medicine','Peyton Rous');
insert into nobel values (1966,'Physics','Alfred Kastler');
insert into nobel values (1965,'Chemistry','Robert B. Woodward');
insert into nobel values (1965,'Literature','Mikhail Sholokhov');
insert into nobel values (1965,'Medicine','François Jacob');
insert into nobel values (1965,'Medicine','André Lwoff');
--- tabnobel, 451, 50
insert into nobel values (1965,'Medicine','Jacques Monod');
insert into nobel values (1965,'Peace','United Nations Children''''s Fund');
insert into nobel values (1965,'Physics','Richard P. Feynman');
insert into nobel values (1965,'Physics','Julian Schwinger');
insert into nobel values (1965,'Physics','Sin-Itiro Tomonaga');
insert into nobel values (1964,'Chemistry','Dorothy Crowfoot Hodgkin');
insert into nobel values (1964,'Literature','Jean-Paul Sartre');
insert into nobel values (1964,'Medicine','Konrad Bloch');
insert into nobel values (1964,'Medicine','Feodor Lynen');
insert into nobel values (1964,'Peace','Martin Luther King Jr.');
insert into nobel values (1964,'Physics','Nicolay G. Basov');
insert into nobel values (1964,'Physics','Aleksandr M. Prokhorov');
insert into nobel values (1964,'Physics','Charles H. Townes');
insert into nobel values (1963,'Chemistry','Giulio Natta');
insert into nobel values (1963,'Chemistry','Karl Ziegler');
insert into nobel values (1963,'Literature','Giorgos Seferis');
insert into nobel values (1963,'Medicine','Sir John Eccles');
insert into nobel values (1963,'Medicine','Alan L. Hodgkin');
insert into nobel values (1963,'Medicine','Andrew F. Huxley');
insert into nobel values (1963,'Peace','International Committee of the Red Cross');
insert into nobel values (1963,'Peace','League of Red Cross Societies');
insert into nobel values (1963,'Physics','Maria Goeppert-Mayer');
insert into nobel values (1963,'Physics','J. Hans D. Jensen');
insert into nobel values (1963,'Physics','Eugene Wigner');
insert into nobel values (1962,'Chemistry','John C. Kendrew');
insert into nobel values (1962,'Chemistry','Max F. Perutz');
insert into nobel values (1962,'Literature','John Steinbeck');
insert into nobel values (1962,'Medicine','Francis Crick');
insert into nobel values (1962,'Medicine','James Watson');
insert into nobel values (1962,'Medicine','Maurice Wilkins');
insert into nobel values (1962,'Peace','Linus Pauling');
insert into nobel values (1962,'Physics','Lev Landau');
insert into nobel values (1961,'Chemistry','Melvin Calvin');
insert into nobel values (1961,'Literature','Ivo Andric');
insert into nobel values (1961,'Medicine','Georg von Békésy');
insert into nobel values (1961,'Peace','Dag Hammarskjöld');
insert into nobel values (1961,'Physics','Robert Hofstadter');
insert into nobel values (1961,'Physics','Rudolf Mössbauer');
insert into nobel values (1960,'Chemistry','Willard F. Libby');
insert into nobel values (1960,'Literature','Saint-John Perse');
insert into nobel values (1960,'Medicine','Sir Frank Macfarlane Burnet');
insert into nobel values (1960,'Medicine','Peter Medawar');
insert into nobel values (1960,'Peace','Albert Lutuli');
insert into nobel values (1960,'Physics','Donald A. Glaser');
insert into nobel values (1959,'Chemistry','Jaroslav Heyrovsky');
insert into nobel values (1959,'Literature','Salvatore Quasimodo');
insert into nobel values (1959,'Medicine','Arthur Kornberg');
insert into nobel values (1959,'Medicine','Severo Ochoa');
insert into nobel values (1959,'Peace','Philip Noel-Baker');
insert into nobel values (1959,'Physics','Owen Chamberlain');
--- tabnobel, 501, 50
insert into nobel values (1959,'Physics','Emilio Segrè');
insert into nobel values (1958,'Chemistry','Frederick Sanger');
insert into nobel values (1958,'Literature','Boris Pasternak');
insert into nobel values (1958,'Medicine','George Beadle');
insert into nobel values (1958,'Medicine','Joshua Lederberg');
insert into nobel values (1958,'Medicine','Edward Tatum');
insert into nobel values (1958,'Peace','Georges Pire');
insert into nobel values (1958,'Physics','Pavel A. Cherenkov');
insert into nobel values (1958,'Physics','Il´ja M. Frank');
insert into nobel values (1958,'Physics','Igor Y. Tamm');
insert into nobel values (1957,'Chemistry','Lord Todd');
insert into nobel values (1957,'Literature','Albert Camus');
insert into nobel values (1957,'Medicine','Daniel Bovet');
insert into nobel values (1957,'Peace','Lester Bowles Pearson');
insert into nobel values (1957,'Physics','Tsung-Dao Lee');
insert into nobel values (1957,'Physics','Chen Ning Yang');
insert into nobel values (1956,'Chemistry','Sir Cyril Hinshelwood');
insert into nobel values (1956,'Chemistry','Nikolay Semenov');
insert into nobel values (1956,'Literature','Juan Ramón Jiménez');
insert into nobel values (1956,'Medicine','André F. Cournand');
insert into nobel values (1956,'Medicine','Werner Forssmann');
insert into nobel values (1956,'Medicine','Dickinson W. Richards');
insert into nobel values (1956,'Physics','John Bardeen');
insert into nobel values (1956,'Physics','Walter H. Brattain');
insert into nobel values (1956,'Physics','William B. Shockley');
insert into nobel values (1955,'Chemistry','Vincent du Vigneaud');
insert into nobel values (1955,'Literature','Halldór Laxness');
insert into nobel values (1955,'Medicine','Hugo Theorell');
insert into nobel values (1955,'Physics','Polykarp Kusch');
insert into nobel values (1955,'Physics','Willis E. Lamb');
insert into nobel values (1954,'Chemistry','Linus Pauling');
insert into nobel values (1954,'Literature','Ernest Hemingway');
insert into nobel values (1954,'Medicine','John F. Enders');
insert into nobel values (1954,'Medicine','Frederick C. Robbins');
insert into nobel values (1954,'Medicine','Thomas H. Weller');
insert into nobel values (1954,'Peace','Office of the United Nations High Commissioner for Refugees');
insert into nobel values (1954,'Physics','Max Born');
insert into nobel values (1954,'Physics','Walther Bothe');
insert into nobel values (1953,'Chemistry','Hermann Staudinger');
insert into nobel values (1953,'Literature','Winston Churchill');
insert into nobel values (1953,'Medicine','Hans Krebs');
insert into nobel values (1953,'Medicine','Fritz Lipmann');
insert into nobel values (1953,'Peace','George C. Marshall');
insert into nobel values (1953,'Physics','Frits Zernike');
insert into nobel values (1952,'Chemistry','Archer J.P. Martin');
insert into nobel values (1952,'Chemistry','Richard L.M. Synge');
insert into nobel values (1952,'Literature','François Mauriac');
insert into nobel values (1952,'Medicine','Selman A. Waksman');
insert into nobel values (1952,'Peace','Albert Schweitzer');
insert into nobel values (1952,'Physics','Felix Bloch');
--- tabnobel, 551, 50
insert into nobel values (1952,'Physics','E. M. Purcell');
insert into nobel values (1951,'Chemistry','Edwin M. McMillan');
insert into nobel values (1951,'Chemistry','Glenn T. Seaborg');
insert into nobel values (1951,'Literature','Pär Lagerkvist');
insert into nobel values (1951,'Medicine','Max Theiler');
insert into nobel values (1951,'Peace','Léon Jouhaux');
insert into nobel values (1951,'Physics','John Cockcroft');
insert into nobel values (1951,'Physics','Ernest T.S. Walton');
insert into nobel values (1950,'Chemistry','Kurt Alder');
insert into nobel values (1950,'Chemistry','Otto Diels');
insert into nobel values (1950,'Literature','Bertrand Russell');
insert into nobel values (1950,'Medicine','Philip S. Hench');
insert into nobel values (1950,'Medicine','Edward C. Kendall');
insert into nobel values (1950,'Medicine','Tadeus Reichstein');
insert into nobel values (1950,'Peace','Ralph Bunche');
insert into nobel values (1950,'Physics','Cecil Powell');
insert into nobel values (1949,'Chemistry','William F. Giauque');
insert into nobel values (1949,'Literature','William Faulkner');
insert into nobel values (1949,'Medicine','Walter Hess');
insert into nobel values (1949,'Medicine','Egas Moniz');
insert into nobel values (1949,'Peace','Lord Boyd Orr');
insert into nobel values (1949,'Physics','Hideki Yukawa');
insert into nobel values (1948,'Chemistry','Arne Tiselius');
insert into nobel values (1948,'Literature','T.S. Eliot');
insert into nobel values (1948,'Medicine','Paul Müller');
insert into nobel values (1948,'Physics','Patrick M.S. Blackett');
insert into nobel values (1947,'Chemistry','Sir Robert Robinson');
insert into nobel values (1947,'Literature','André Gide');
insert into nobel values (1947,'Medicine','Carl Cori');
insert into nobel values (1947,'Medicine','Gerty Cori');
insert into nobel values (1947,'Medicine','Bernardo Houssay');
insert into nobel values (1947,'Peace','Friends Service Council');
insert into nobel values (1947,'Peace','American Friends Service Committee');
insert into nobel values (1947,'Physics','Edward V. Appleton');
insert into nobel values (1946,'Chemistry','John H. Northrop');
insert into nobel values (1946,'Chemistry','Wendell M. Stanley');
insert into nobel values (1946,'Chemistry','James B. Sumner');
insert into nobel values (1946,'Literature','Hermann Hesse');
insert into nobel values (1946,'Medicine','Hermann J. Muller');
insert into nobel values (1946,'Peace','Emily Greene Balch');
insert into nobel values (1946,'Peace','John R. Mott');
insert into nobel values (1946,'Physics','Percy W. Bridgman');
insert into nobel values (1945,'Chemistry','Artturi Virtanen');
insert into nobel values (1945,'Literature','Gabriela Mistral');
insert into nobel values (1945,'Medicine','Ernst B. Chain');
insert into nobel values (1945,'Medicine','Sir Alexander Fleming');
insert into nobel values (1945,'Medicine','Sir Howard Florey');
insert into nobel values (1945,'Peace','Cordell Hull');
insert into nobel values (1945,'Physics','Wolfgang Pauli');
insert into nobel values (1944,'Chemistry','Otto Hahn');
--- tabnobel, 601, 50
insert into nobel values (1944,'Literature','Johannes V. Jensen');
insert into nobel values (1944,'Medicine','Joseph Erlanger');
insert into nobel values (1944,'Medicine','Herbert S. Gasser');
insert into nobel values (1944,'Peace','International Committee of the Red Cross');
insert into nobel values (1944,'Physics','Isidor Isaac Rabi');
insert into nobel values (1943,'Chemistry','George de Hevesy');
insert into nobel values (1943,'Medicine','Henrik Dam');
insert into nobel values (1943,'Medicine','Edward A. Doisy');
insert into nobel values (1943,'Physics','Otto Stern');
insert into nobel values (1939,'Chemistry','Adolf Butenandt');
insert into nobel values (1939,'Chemistry','Leopold Ruzicka');
insert into nobel values (1939,'Literature','Frans Eemil Sillanpää');
insert into nobel values (1939,'Medicine','Gerhard Domagk');
insert into nobel values (1939,'Physics','Ernest Lawrence');
insert into nobel values (1938,'Chemistry','Richard Kuhn');
insert into nobel values (1938,'Literature','Pearl Buck');
insert into nobel values (1938,'Medicine','Corneille Heymans');
insert into nobel values (1938,'Peace','Nansen International Office for Refugees');
insert into nobel values (1938,'Physics','Enrico Fermi');
insert into nobel values (1937,'Chemistry','Norman Haworth');
insert into nobel values (1937,'Chemistry','Paul Karrer');
insert into nobel values (1937,'Literature','Roger Martin du Gard');
insert into nobel values (1937,'Medicine','Albert Szent-Györgyi');
insert into nobel values (1937,'Peace','Robert Cecil');
insert into nobel values (1937,'Physics','Clinton Davisson');
insert into nobel values (1937,'Physics','George Paget Thomson');
insert into nobel values (1936,'Chemistry','Peter Debye');
insert into nobel values (1936,'Literature','Eugene O''''Neill');
insert into nobel values (1936,'Medicine','Sir Henry Dale');
insert into nobel values (1936,'Medicine','Otto Loewi');
insert into nobel values (1936,'Peace','Carlos Saavedra Lamas');
insert into nobel values (1936,'Physics','Carl D. Anderson');
insert into nobel values (1936,'Physics','Victor F. Hess');
insert into nobel values (1935,'Chemistry','Frédéric Joliot');
insert into nobel values (1935,'Chemistry','Irène Joliot-Curie');
insert into nobel values (1935,'Medicine','Hans Spemann');
insert into nobel values (1935,'Peace','Carl von Ossietzky');
insert into nobel values (1935,'Physics','James Chadwick');
insert into nobel values (1934,'Chemistry','Harold C. Urey');
insert into nobel values (1934,'Literature','Luigi Pirandello');
insert into nobel values (1934,'Medicine','George R. Minot');
insert into nobel values (1934,'Medicine','William P. Murphy');
insert into nobel values (1934,'Medicine','George H. Whipple');
insert into nobel values (1934,'Peace','Arthur Henderson');
insert into nobel values (1933,'Literature','Ivan Bunin');
insert into nobel values (1933,'Medicine','Thomas H. Morgan');
insert into nobel values (1933,'Peace','Sir Norman Angell');
insert into nobel values (1933,'Physics','Paul A.M. Dirac');
insert into nobel values (1933,'Physics','Erwin Schrödinger');
insert into nobel values (1932,'Chemistry','Irving Langmuir');
--- tabnobel, 651, 50
insert into nobel values (1932,'Literature','John Galsworthy');
insert into nobel values (1932,'Medicine','Edgar Adrian');
insert into nobel values (1932,'Medicine','Sir Charles Sherrington');
insert into nobel values (1932,'Physics','Werner Heisenberg');
insert into nobel values (1931,'Chemistry','Friedrich Bergius');
insert into nobel values (1931,'Chemistry','Carl Bosch');
insert into nobel values (1931,'Literature','Erik Axel Karlfeldt');
insert into nobel values (1931,'Medicine','Otto Warburg');
insert into nobel values (1931,'Peace','Jane Addams');
insert into nobel values (1931,'Peace','Nicholas Murray Butler');
insert into nobel values (1930,'Chemistry','Hans Fischer');
insert into nobel values (1930,'Literature','Sinclair Lewis');
insert into nobel values (1930,'Medicine','Karl Landsteiner');
insert into nobel values (1930,'Peace','Nathan Söderblom');
insert into nobel values (1930,'Physics','Sir Venkata Raman');
insert into nobel values (1929,'Chemistry','Arthur Harden');
insert into nobel values (1929,'Chemistry','Hans von Euler-Chelpin');
insert into nobel values (1929,'Literature','Thomas Mann');
insert into nobel values (1929,'Medicine','Christiaan Eijkman');
insert into nobel values (1929,'Medicine','Sir Frederick Hopkins');
insert into nobel values (1929,'Peace','Frank B. Kellogg');
insert into nobel values (1929,'Physics','Louis de Broglie');
insert into nobel values (1928,'Chemistry','Adolf Windaus');
insert into nobel values (1928,'Literature','Sigrid Undset');
insert into nobel values (1928,'Medicine','Charles Nicolle');
insert into nobel values (1928,'Physics','Owen Willans Richardson');
insert into nobel values (1927,'Chemistry','Heinrich Wieland');
insert into nobel values (1927,'Literature','Henri Bergson');
insert into nobel values (1927,'Medicine','Julius Wagner-Jauregg');
insert into nobel values (1927,'Peace','Ferdinand Buisson');
insert into nobel values (1927,'Peace','Ludwig Quidde');
insert into nobel values (1927,'Physics','Arthur H. Compton');
insert into nobel values (1927,'Physics','C.T.R. Wilson');
insert into nobel values (1926,'Chemistry','The Svedberg');
insert into nobel values (1926,'Literature','Grazia Deledda');
insert into nobel values (1926,'Medicine','Johannes Fibiger');
insert into nobel values (1926,'Peace','Aristide Briand');
insert into nobel values (1926,'Peace','Gustav Stresemann');
insert into nobel values (1926,'Physics','Jean Baptiste Perrin');
insert into nobel values (1925,'Chemistry','Richard Zsigmondy');
insert into nobel values (1925,'Literature','George Bernard Shaw');
insert into nobel values (1925,'Peace','Sir Austen Chamberlain');
insert into nobel values (1925,'Peace','Charles G. Dawes');
insert into nobel values (1925,'Physics','James Franck');
insert into nobel values (1925,'Physics','Gustav Hertz');
insert into nobel values (1924,'Literature','Wladyslaw Reymont');
insert into nobel values (1924,'Medicine','Willem Einthoven');
insert into nobel values (1924,'Physics','Manne Siegbahn');
insert into nobel values (1923,'Chemistry','Fritz Pregl');
insert into nobel values (1923,'Literature','William Butler Yeats');
--- tabnobel, 701, 50
insert into nobel values (1923,'Medicine','Frederick G. Banting');
insert into nobel values (1923,'Medicine','John Macleod');
insert into nobel values (1923,'Physics','Robert A. Millikan');
insert into nobel values (1922,'Chemistry','Francis W. Aston');
insert into nobel values (1922,'Literature','Jacinto Benavente');
insert into nobel values (1922,'Medicine','Archibald V. Hill');
insert into nobel values (1922,'Medicine','Otto Meyerhof');
insert into nobel values (1922,'Peace','Fridtjof Nansen');
insert into nobel values (1922,'Physics','Niels Bohr');
insert into nobel values (1921,'Chemistry','Frederick Soddy');
insert into nobel values (1921,'Literature','Anatole France');
insert into nobel values (1921,'Peace','Hjalmar Branting');
insert into nobel values (1921,'Peace','Christian Lange');
insert into nobel values (1921,'Physics','Albert Einstein');
insert into nobel values (1920,'Chemistry','Walther Nernst');
insert into nobel values (1920,'Literature','Knut Hamsun');
insert into nobel values (1920,'Medicine','August Krogh');
insert into nobel values (1920,'Peace','Léon Bourgeois');
insert into nobel values (1920,'Physics','Charles Edouard Guillaume');
insert into nobel values (1919,'Literature','Carl Spitteler');
insert into nobel values (1919,'Medicine','Jules Bordet');
insert into nobel values (1919,'Peace','Woodrow Wilson');
insert into nobel values (1919,'Physics','Johannes Stark');
insert into nobel values (1918,'Chemistry','Fritz Haber');
insert into nobel values (1918,'Physics','Max Planck');
insert into nobel values (1917,'Literature','Karl Gjellerup');
insert into nobel values (1917,'Literature','Henrik Pontoppidan');
insert into nobel values (1917,'Peace','International Committee of the Red Cross');
insert into nobel values (1917,'Physics','Charles Glover Barkla');
insert into nobel values (1916,'Literature','Verner von Heidenstam');
insert into nobel values (1915,'Chemistry','Richard Willstätter');
insert into nobel values (1915,'Literature','Romain Rolland');
insert into nobel values (1915,'Physics','William Bragg');
insert into nobel values (1915,'Physics','Lawrence Bragg');
insert into nobel values (1914,'Chemistry','Theodore W. Richards');
insert into nobel values (1914,'Medicine','Robert Bárány');
insert into nobel values (1914,'Physics','Max von Laue');
insert into nobel values (1913,'Chemistry','Alfred Werner');
insert into nobel values (1913,'Literature','Rabindranath Tagore');
insert into nobel values (1913,'Medicine','Charles Richet');
insert into nobel values (1913,'Peace','Henri La Fontaine');
insert into nobel values (1913,'Physics','Heike Kamerlingh Onnes');
insert into nobel values (1912,'Chemistry','Victor Grignard');
insert into nobel values (1912,'Chemistry','Paul Sabatier');
insert into nobel values (1912,'Literature','Gerhart Hauptmann');
insert into nobel values (1912,'Medicine','Alexis Carrel');
insert into nobel values (1912,'Peace','Elihu Root');
insert into nobel values (1912,'Physics','Gustaf Dalén');
insert into nobel values (1911,'Chemistry','Marie Curie');
insert into nobel values (1911,'Literature','Maurice Maeterlinck');
--- tabnobel, 751, 50
insert into nobel values (1911,'Medicine','Allvar Gullstrand');
insert into nobel values (1911,'Peace','Tobias Asser');
insert into nobel values (1911,'Peace','Alfred Fried');
insert into nobel values (1911,'Physics','Wilhelm Wien');
insert into nobel values (1910,'Chemistry','Otto Wallach');
insert into nobel values (1910,'Literature','Paul Heyse');
insert into nobel values (1910,'Medicine','Albrecht Kossel');
insert into nobel values (1910,'Peace','Permanent International Peace Bureau');
insert into nobel values (1910,'Physics','Johannes Diderik van der Waals');
insert into nobel values (1909,'Chemistry','Wilhelm Ostwald');
insert into nobel values (1909,'Literature','Selma Lagerlöf');
insert into nobel values (1909,'Medicine','Theodor Kocher');
insert into nobel values (1909,'Peace','Auguste Beernaert');
insert into nobel values (1909,'Peace','Paul Henri d''''Estournelles de Constant');
insert into nobel values (1909,'Physics','Ferdinand Braun');
insert into nobel values (1909,'Physics','Guglielmo Marconi');
insert into nobel values (1908,'Chemistry','Ernest Rutherford');
insert into nobel values (1908,'Literature','Rudolf Eucken');
insert into nobel values (1908,'Medicine','Paul Ehrlich');
insert into nobel values (1908,'Medicine','Ilya Mechnikov');
insert into nobel values (1908,'Peace','Klas Pontus Arnoldson');
insert into nobel values (1908,'Peace','Fredrik Bajer');
insert into nobel values (1908,'Physics','Gabriel Lippmann');
insert into nobel values (1907,'Chemistry','Eduard Buchner');
insert into nobel values (1907,'Literature','Rudyard Kipling');
insert into nobel values (1907,'Medicine','Alphonse Laveran');
insert into nobel values (1907,'Peace','Ernesto Teodoro Moneta');
insert into nobel values (1907,'Peace','Louis Renault');
insert into nobel values (1907,'Physics','Albert A. Michelson');
insert into nobel values (1906,'Chemistry','Henri Moissan');
insert into nobel values (1906,'Literature','Giosuè Carducci');
insert into nobel values (1906,'Medicine','Camillo Golgi');
insert into nobel values (1906,'Medicine','Santiago Ramón y Cajal');
insert into nobel values (1906,'Peace','Theodore Roosevelt');
insert into nobel values (1906,'Physics','J.J. Thomson');
insert into nobel values (1905,'Chemistry','Adolf von Baeyer');
insert into nobel values (1905,'Literature','Henryk Sienkiewicz');
insert into nobel values (1905,'Medicine','Robert Koch');
insert into nobel values (1905,'Peace','Bertha von Suttner');
insert into nobel values (1905,'Physics','Philipp Lenard');
insert into nobel values (1904,'Chemistry','Sir William Ramsay');
insert into nobel values (1904,'Literature','José Echegaray');
insert into nobel values (1904,'Literature','Frédéric Mistral');
insert into nobel values (1904,'Medicine','Ivan Pavlov');
insert into nobel values (1904,'Peace','Institute of International Law');
insert into nobel values (1904,'Physics','Lord Rayleigh');
insert into nobel values (1903,'Chemistry','Svante Arrhenius');
insert into nobel values (1903,'Literature','Bjørnstjerne Bjørnson');
insert into nobel values (1903,'Medicine','Niels Ryberg Finsen');
insert into nobel values (1903,'Peace','Randal Cremer');
--- tabnobel, 801, 50
insert into nobel values (1903,'Physics','Henri Becquerel');
insert into nobel values (1903,'Physics','Pierre Curie');
insert into nobel values (1903,'Physics','Marie Curie');
insert into nobel values (1902,'Chemistry','Emil Fischer');
insert into nobel values (1902,'Literature','Theodor Mommsen');
insert into nobel values (1902,'Medicine','Ronald Ross');
insert into nobel values (1902,'Peace','Élie Ducommun');
insert into nobel values (1902,'Peace','Albert Gobat');
insert into nobel values (1902,'Physics','Hendrik A. Lorentz');
insert into nobel values (1902,'Physics','Pieter Zeeman');
insert into nobel values (1901,'Chemistry','Jacobus H. van ''''t Hoff');
insert into nobel values (1901,'Literature','Sully Prudhomme');
insert into nobel values (1901,'Medicine','Emil von Behring');
insert into nobel values (1901,'Peace','Henry Dunant');
insert into nobel values (1901,'Peace','Frédéric Passy');
insert into nobel values (1901,'Physics','Wilhelm Conrad Röntgen');
